### ISSUE TITLE
A template for using r2u?

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/devcontainer-templates#19]
I am wondering if it is worth adding something like <https://github.com/grantmcdermott/codespaces-r2u> as a Template.

I didn't see the need to make it a Template since this would only add the `r-apt` Feature to ubuntu, but things like vscode-R settings are not included in the Feature so there may be value in being able to copy this from the beginning.

Note: The platform must be enforced to amd64 as arm64 is not supported.

@grantmcdermott Any thoughts?

**Comment by eddelbuettel** [comment]
I'd be in favor, but I am not without bias here. For what it is worth I did a quick try this afternoon using

```yaml
  "ghcr.io/rocker-org/devcontainer-features/r-apt:0": {
    // See: https://github.com/rocker-org/devcontainer-features/blob/main/src/r-apt/README.md#options
    "vscodeRSupport": "full",
    "installBspm": true,
    "installRadian": false,
    "installDevTools": false,
    "installRMarkdown": false,
    "installVscDebugger": false,
    "useTesting": false
    }
```

Initial start is still not as fast as I'd would wish for but that is just a one-off cost. Works otherwise and is lovely.  (I also turned the obnoxious linter off.)
